#!/usr/bin/env zsh

file="$1"; shift
case "$(basename "$file" | tr '[:upper:]' '[:lower:]')" in
#*.tar*) tar tf "$file" ;;
#*.zip) unzip -l "$file" ;;
#*.rar) unrar l "$file" ;;
#*.7z) 7z l "$file" ;;
*.avi|*.mp4|*.mkv|*.webm)
	mpv "$file"
	exit
	;;
*.pdf|*.ps|*.djvu|*.epub)
	okular "$file"
	exit
	;;
*.odt|*.ods|*.odp|*.odg|*.odf|*.odb|*.doc|*.docx)
	# FIXME: soffice crashes when launched via shell-async '&soffice'
	soffice "$file" >/tmp/barz 2>&1
	exit
	;;
*.jpg|*.jpeg|*.png|*.bmp|*.tiff)
	sxiv "$file"
	exit
	;;
*.svg)
	inkscape "$file"
	exit
	;;
*.gif)
	sxiv -a "$file"
	exit
	;;
*)
	echo "nvim $file" | zshxi
	exit
	;;
esac
