#!/usr/bin/env bash

FILEPATH_ABS="$1"
lf_previewbox_x="$4"
lf_previewbox_y="$5"
lf_previewbox_w="$2"
lf_previewbox_h="$3"

# HACK:Previewbox parameter width seems off by 2, dunno why
lf_previewbox_w=$(( $lf_previewbox_w - 2 ))

preview_image() {
	filepath="$1"

	chafa --animate false --view-size "${lf_previewbox_w}x${lf_previewbox_h}" "$filepath"
}

preview_archive() (
	trap "exit 1" ERR
	set -eo pipefail
	filepath="$1"

	case "$1" in
		*.tar|*.tar.*)
			tar -tf "$filepath"
		;;
		*.zip)
			zipinfo -1 "$filepath"
		;;
		*.7z)
			# https://stackoverflow.com/a/68070379
			7z l -ba "$filepath" | grep -oP '(?<=^.{53}).*'
		;;
		*.rar)
			rar lb "$filepath"
		;;
	esac                                                 | \
		tree -L 1 -F --dirsfirst --noreport --fromfile . | \
		fold -w "$lf_previewbox_w"
)

# # Preview "$1"'s file content as text using '-' for stdin. Use as common text
# # preview wrapper, so that pagination will apply to text aswell. '-p' disables
# # fancy output.
# preview_text() {
# 	if [ "$1" = "-p" ]; then
# 		shift
# 		bat -P -f -r "$page:" --style plain "$1"
# 	else
# 		bat -P -f -r "$page:" --style "grid,numbers" "$1"
# 	fi
# }

# thumbnail_abspath="$LFBUNDLE_TEMPDIR/thumbnail.png" # thumbnail path for ad-hoc conversions
# page="$(cat "$LFBUNDLE_TEMPDIR/page")" # pagination offset

# # BUG: lf displays stdout output offset by two cells to the right with respect
# # to the preview box's boundaries. In order to align image previews with text
# # we add that offset to the preview coordinates.
# IMAGE_PREVIEWBOX_X=$((lf_previewbox_x+2)); IMAGE_PREVIEWBOX_W=$((lf_previewbox_w-2))

# Determine the number of lines required for the full filename to be displayed
# and add that to the y-offset for image previews. Add another offset for the
# horizontal separator line.

THUMBNAIL_ABSPATH="$LFBUNDLE_TEMPDIR/thumbnail.png" # thumbnail path for ad-hoc conversions

# Generates file previews. Returns nonzero return code if an error occurs.
generate_preview() (
	trap "exit 1" ERR
	set -eo pipefail
	filepath="$1"

	filename="$(basename "$filepath")"
	case "$(echo "$filename" | tr '[:upper:]' '[:lower:]')" in
	*.pdf|*.ps)
		gs -o "$THUMBNAIL_ABSPATH" -sDEVICE=pngalpha "$filepath" >/dev/null
		preview_image "$THUMBNAIL_ABSPATH"
		;;
	*.jpg|*.jpeg|*.png|*.bmp|*.tiff|*.gif|*.svg)
		preview_image "$filepath"
		;;
	*.avi|*.webm|*.webp|*.mp4|*.mkv)
		ffmpeg -y -i "$filepath" -vframes 1 "$THUMBNAIL_ABSPATH"
		preview_image "$THUMBNAIL_ABSPATH"
		;;
	*.tar|*.tar.*|*.7z|*.rar|*.zip)
		preview_archive "$filepath"
		;;
	*.iso)
		iso-info --no-header "$filepath" | \
			fold -w "$lf_previewbox_w"
		;;
	*.drawio)
		drawio -x -f png -o "$THUMBNAIL_ABSPATH" "$filepath" >/dev/null 2>&1
		preview_image "$THUMBNAIL_ABSPATH"
		;;
	*)
		bat --style plain --color always --terminal-width "$lf_previewbox_w" "$filepath"
		;;
	esac
)

preview="$(generate_preview "$FILEPATH_ABS")"
if [[ "$?" == 0 ]]; then
	echo "$preview"
else
	echo "Error generating preview, using 'file':"
	file "$FILEPATH_ABS" | fold -w "$lf_previewbox_w"
fi

# *.odt|*.ods|*.odp|*.odg|*.odf|*.odb|*.doc|*.docx)
# 	echo
# 	soffice --cat "$abspath" | preview_text -p -
# 	;;
# *.djvu)
# 	buffer="$LFBUNDLE_TEMPDIR/buffer.tiff"
# 	ddjvu -page="$page" -format=tiff "$abspath" "$buffer"
# 	gm convert "$buffer" "$thumbnail_abspath"
# 	preview_image "$thumbnail_abspath"
# 	;;
# *.iso)
# 	iso-info --no-header "$abspath" | tail -n +2 | preview_text -p -
# 	;;
# *) preview_text "$abspath"
# 	;;
# esac
#

return 127 # nonzero retcode to disable preview caching
