#!/usr/bin/env sh

preview() {
	cat <<-EOF | paste -sd '' >"$LFBUNDLE_TEMPDIR/ueberzug_fifo"
	{
	"action": "add", "identifier": "lfbundle-preview",
	"path": "$1", "x": $(($4 + 2)), "y": $(($5 + 1)), "width": $(($2 - 1)), "height": $(($3 - 1)),
	"scaler": "contain"
	}
	EOF
}

fullpath="$1"; shift
page="$(cat $LFBUNDLE_TEMPDIR/page)"
thumbnail="$LFBUNDLE_TEMPDIR/thumbnail.png"
filename="$(basename "$fullpath")"

echo "\033[1;38;5;253m$filename\033[0m"
case "$(echo "$filename" | tr '[:upper:]' '[:lower:]')" in
*.tar*) tar tf "$fullpath" ;;
*.zip) unzip -l "$fullpath" ;;
*.rar) unrar l "$fullpath" ;;
*.7z) 7z l "$fullpath" ;;
*.avi|*.mp4|*.mkv|*.webm)
	ffmpeg -y -i "$fullpath" -vframes 1 "$thumbnail"
	preview "$thumbnail" "$@"
	;;
*.pdf|*.ps)
	gs -o "$thumbnail" -sDEVICE=pngalpha -dFirstPage=$page -dLastPage=$page "$fullpath" >/dev/null
	preview "$thumbnail" "$@"
	;;
*.odt|*.ods|*.odp|*.odg|*.odf|*.odb|*.doc|*.docx)
	echo
	soffice --cat "$fullpath"
	;;
*.djvu)
	buffer="$LFBUNDLE_TEMPDIR/buffer.tiff"
	ddjvu -page=$page -format=tiff "$fullpath" "$buffer"
	gm convert "$buffer" "$thumbnail"
	preview "$thumbnail" "$@"
	;;
*.jpg|*.jpeg|*.png|*.bmp|*.tiff)
	preview "$fullpath" "$@" ;;
*.svg)
	gm convert "$fullpath" "$thumbnail"
	preview "$thumbnail" "$@"
	;;
*.gif)
	gm convert "$fullpath[$page]" "$thumbnail"
	preview "$thumbnail" "$@"
	;;
*.iso)
	echo
	iso-info --no-header "$fullpath" | tail -n +2
	;;
*) bat -P -f --terminal-width $W -r "$page:" --style "grid,numbers" "$fullpath"
	;;
esac
return 127 # nonzero retcode disable preview caching.
